server:
  port: 7012
  address: 0.0.0.0
spring:
  application:
    name: ms-simecr
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db_simecr
    username: postgres
    password: 213141
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  sql:
    init:
      mode: always
keycloak:
  realm: simecr
  bearer-only: true
  use-resource-role-mappings: true
  auth-server-url: http://127.0.0.1:8080/auth
  resource: simecr-backend
  credentials:
    secret: d731bfad-3400-4fcf-b05f-23d5e043a3fd
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ms-simecr
  client:
    service-url:
      defaultZone: http://10.0.9.11:91/eureka
    enabled: false
feign:
  circuitbreaker:
    enabled: true

periodo: 2022
pia: 314543498.00
service:
  persona:
    url: http://127.0.0.1:7006
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: NOGZ3QDD9D7D3Q951X1E
      secret-key: MBWLAtC4MyOPeV4x9eGBgF8TLCvhoK16r4gPRo1x
    s3:
      endpoint: ewr1.vultrobjects.com
    sqs:
      endpoint: ewr1.vultrobjects.com
    rds:
      endpoint: ewr1.vultrobjects.com