server:
  port: 7012
  address: 10.0.9.11
spring:
  application:
    name: ms-simecr
  datasource:
    url: jdbc:postgresql://10.0.9.11:5432/db_simecr
    username: postgres
    password: RegionCusco@2018
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  sql:
    init:
      mode: always
keycloak:
  realm: sipac
  bearer-only: true
  use-resource-role-mappings: true
  auth-server-url: http://oauth.regioncusco.gob.pe/auth
  resource: simecr-backend
  credentials:
    secret: 28765a50-ebe9-4a89-936a-f9fc128b89dc
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ms-simecr
  client:
    service-url:
      defaultZone: http://10.0.9.11:91/eureka
service:
  persona:
    url: http://10.0.9.11:7005
periodo: 2022
pia: 314543498.00
